### ISSUE TITLE
Hardcoded value for script URL.

### ISSUE THREAD

**Issue by blouze** [c316/doorbell#1]
Hey @c316 !

Cool idea. I just started using Doorbell myself.
Unfortunately, your package was no use for me as the code (and link) they give you depends on the app.

**Comment by c316** [comment]
@blouze Thanks for the feedback, sorry the package wasn't useful for you. 

I've updated the package to separate the button URL code. Put that URL into the ```Meteor.settings.public.buttonURL``` and let me know if it works for you. 

Thanks
